version: "3"
tunnels:
    api:
        proto: http
        addr: 8001
        domain: weco-proto-api.ngrok.io
    frontend:
        proto: http
        addr: 3000
        domain: weco-proto-type.ngrok.io
        request_header:
            add:
                - "ngrok-skip-browser-warning: true"
agent:
    authtoken: 3DIcgwZIwLqMAcL3ffjUvyscduD_5t1Q85kvpyjeprRKYxBrX
